[project]
name = "research-task-traders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "IDK", email = "idk" }
]
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "massive>=2.8.0",
    "requests>=2.34.2",
]

[project.scripts]
research-task-traders = "research_task_traders:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
